### ISSUE TITLE
NoneType object on autobahn

### ISSUE THREAD

**Issue by efialtisgr** [mahendrakalkura/diffusion#3]
```
2019-01-18T20:00:36+0000 RX compressed [length]: octets
2019-01-18T20:00:36+0000 Unhandled Error
Traceback (most recent call last):
  File "manage.py", line 11, in main
    reactor.run()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1243, in run
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1255, in mainLoop
    self.doIteration(t)
  File "C:\Python27\lib\site-packages\twisted\internet\selectreactor.py", line 143, in doSelect
    _logrun(selectable, _drdw, selectable, method)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "C:\Python27\lib\site-packages\twisted\internet\selectreactor.py", line 154, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, method=="doRead")
  File "C:\Python27\lib\site-packages\twisted\internet\posixbase.py", line 258, in _disconnectSelectable
    selectable.connectionLost(failure.Failure(why))
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 478, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 292, in connectionLost
    protocol.connectionLost(reason)
  File "C:\Python27\lib\site-packages\twisted\protocols\tls.py", line 398, in connectionLost
    self._flushReceiveBIO()
  File "C:\Python27\lib\site-packages\twisted\protocols\tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "C:\Python27\lib\site-packages\twisted\protocols\policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "C:\Python27\lib\site-packages\autobahn\twisted\websocket.py", line 131, in dataReceived
    self._dataReceived(data)
  File "C:\Python27\lib\site-packages\autobahn\websocket\protocol.py", line 1175, in _dataReceived
    self.consumeData()
  File "C:\Python27\lib\site-packages\autobahn\websocket\protocol.py", line 1187, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "C:\Python27\lib\site-packages\autobahn\websocket\protocol.py", line 1545, in processData
    fr = self.onFrameData(payload)
  File "C:\Python27\lib\site-packages\autobahn\websocket\protocol.py", line 1639, in onFrameData
    self._onMessageFrameData(payload)
  File "C:\Python27\lib\site-packages\autobahn\twisted\websocket.py", line 150, in _onMessageFrameData
    self.onMessageFrameData(payload)
  File "C:\Python27\lib\site-packages\autobahn\websocket\protocol.py", line 601, in onMessageFrameData
    self.frame_data.append(payload)
exceptions.AttributeError: 'NoneType' object has no attribute 'append'
```

**Comment by mahendrakalkura** [comment]
Please provide additional details.

**Comment by efialtisgr** [comment]
I cant reproduce the error probably an error from 3 65 .
